name: Flutter-Android-iOS-Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # Create the GitHub release if it does not exist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: v1.0
          body: "Automated release including the latest APK and IPA."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          tag: v1.0
          overwrite: true
          body: "This release includes both Android APK and iOS IPA builds."

  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: flutter pub get

      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Prepare Payload
        run: mkdir Payload && mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip IPA
        run: zip -qq -r FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Create the GitHub release if it does not exist (safe to call again)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: v1.0
          body: "Automated release including the latest APK and IPA."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This release includes both Android APK and iOS IPA builds."
